### ISSUE TITLE
Page restarts after a while in the background

### ISSUE THREAD

**Issue by RaulWhite** [RaulWhite/youtubeAudio#1]
If the page has an audio playing, and it's in the background like for two minutes, when you come back to the page, it resets to the initial state (like if you refresh it).

Browser: Mozilla Firefox 59.0.2-2

**Comment by melchor629** [comment]
OS?

On Safari works well 💪🏿👌🏿👌🏿

**Comment by RaulWhite** [comment]
Closing due to being stalled
